### ISSUE TITLE
Feature Request: More ordering options?

### ISSUE THREAD

**Issue by ImmutableOctet** [engor/Ted2Go#10]
Is it possible to add options for different ordering modes for the right pane? It currently shows source-code identifiers (Classes, methods, etc) in alphabetical order, rather than order-of-appearance. Is it possible to provide this option? If not, is this something we can get Mark to help with?

As a follow-up question, can the debug-stack be reversible? It's currently bottom-to-top in order of appearance (Making it a retroactive queue). It would be cool to have the option to reverse it so the current function is on the bottom, with 'Main' being at the top.

Here's some comparisons:

**Source** | *Left*: Accurate | *Right*: Inaccurate (Alphabetical)
![ted1_vs_ted2_source](https://cloud.githubusercontent.com/assets/3187882/20841698/f88bd0d4-b871-11e6-87f3-f8faef85de45.png)

**Debug** | *Left*: Top-to-Bottom | *Right*: Bottom-to-Top
![ted1_vs_ted2](https://cloud.githubusercontent.com/assets/3187882/20841555/73d15148-b871-11e6-9595-1224f0d3d673.png)

Thoughts?

**Comment by engor** [comment]
Ok, I like Top-to-Bottom sorting for debugger too.
Settings option for sort-by-sorces - yes. But not all at once. :)

**Comment by engor** [comment]
Added toggles - sort by type / source and show inherited.
I tried to rearrange debug data but I can't. Need to ask to Mark about it.
