### ISSUE TITLE
Make errors pane optional...

### ISSUE THREAD

**Issue by blitz-research** [engor/Ted2Go#100]
Hi,

I think the 'errors' pane that splits the build console in half should be optional, as I often find it just ends up preventing me from quickly seeing what errors have occured, esp. if there's just a handful of errors.

It's quite useful in the case of building modules as it allows you to see errors without them scrolling out of view due to module build output, but for building apps I find it a lot less useful.

Bye,
Mark

**Comment by engor** [comment]
Hi. 
I've improved Console view, so now you can to jump to files with error right from console - just click on error line number! (cursor changed to Hand here)
And 'errors list' was totally removed.
Try it out.

**Comment by blitz-research** [comment]
Much better thanks, however with latest dev version both 'blitzed' and
'classic dark' themes the autocomplete colors seemed to be a bit messed up,
selected item is always blank as if foreground/background colors are both
white,.

Pretty sure these themes used to work with autocomplete....


On Mon, Jan 22, 2018 at 5:17 AM, Evgeniy Goroshkin <notifications@github.com

**Comment by engor** [comment]
I created own issue #103 related to colors of completion list.
Some colors are hardcoded there.

**Comment by blitz-research** [comment]
>  just click on error line number! (cursor changed to Hand here)

Very cool!
