### ISSUE TITLE
Opening double-clicked files

### ISSUE THREAD

**Issue by DruggedBunny** [engor/Ted2Go#101]
I have _\bin\ted2_windows\Ted2.exe_ set to open .monkey2 files by default.

Double-clicking them opens Ted2Go, adds it to the open tabs, but doesn't make it the active tab -- could this be changed? I would assume anyone launching the editor via a specific file would want it to switch to that file.

(I suppose it's possible someone could launch with > 1 file, but in that case, there's no way to tell which one they want to switch to by default, so I would just make the last-loaded file the active tab in that case.)

On a related point, could Ted2Go pick up command-line parameters (including .monkey2 files) from the launcher? It feels kinda hacky to have to set a hidden binary to be the main file, and seems to make _Monkey2 (Windows).exe_ redundant.

**Comment by engor** [comment]
Will fix that.

> On a related point, could Ted2Go pick up command-line parameters (including .monkey2 files) from the launcher?

Yes, the launcher  passes params into ted2.exe, so you can set launcher to open files.

**Comment by engor** [comment]
Should be fixed it `dev` branch.
