### ISSUE TITLE
More use of Esc

### ISSUE THREAD

**Issue by DruggedBunny** [engor/Ted2Go#102]
A few things bug me in Ted2Go which I think would be resolved via more use of Esc:

1) Those pop-up parameter hints -- I always try to hide them by hitting Esc, closing the console instead. I have to move the cursor away to get rid of them.
_I would just treat these pop-ups as a priority when Esc is hit, ie. if one of these is open, don't toggle the console, close the pop-up._
2) Shift-F5 to stop compilation -- I find it hard to remember/perform this combination quickly enough to stop compilation!
_I think that while the Build console is being actively used for compilation output, Esc should stop the build rather than toggle the console._ (Next press of Esc would of course toggle again.)

Also, relating to 2) -- could we print "Compilation terminated" or similar to the console, to show that it's been recognised? I always sit there wondering if it's still building, as there's no feedback!

**Comment by engor** [comment]
1. and 3. Now done in `dev` branch.
2. There is a button with cross-icon in status bar to stop process
![stop-process](https://user-images.githubusercontent.com/5233803/35225676-8aa9db1e-ffbb-11e7-94bb-a924c350702d.jpg)

**Comment by DruggedBunny** [comment]
Yeah, I've seen that, but if I'm hands-on the keyboard, then I'm too slow moving over to the mouse and trying to click the button!

Thanks for adding the other stuff! However, I think the latest develop version of monkey2 has broken Ted2Go -- see separate issue "Latest monkey2-develop has broken Ted2Go"!

Thanks again.

**Comment by engor** [comment]
F5 - run
Shift+F5 - stop.
easy... :)

Also you can re-run app/game by single F5 - if app is already running then pressing F5 will stop current one and run new one, so you can re-run without stopping by yourself.
