### ISSUE TITLE
Latest monkey2-develop has broken Ted2Go

### ISSUE THREAD

**Issue by DruggedBunny** [engor/Ted2Go#104]
This is what I get right now after checking out latest mx2 and Ted2Go (both develop versions):

```
***** Rebuilding ted2 *****

Mx2cc version 1.1.09

***** Making app 'I:/SpiderOak/DevTools/Monkey2/mx2builder/monkey2/src/ted2go/Te
d2.monkey2' (windows release x86 gcc) *****

Parsing...
Semanting...
I:/SpiderOak/DevTools/Monkey2/mx2builder/monkey2/src/ted2go/document/SceneDocume
nt.monkey2 [47] : Error : Can't find overload for 'Render' with argument types (
mojo.graphics.Canvas,mojo3d.Camera)

```
I assume this relates to _"Camera param removed from Scene.Render. Scene.Render now renders all cameras in a scene. Add Camera.Render for just rendering a single camera - this is now recommended way to render a scene, multiple cameras not dealt with yet"_ from [latest VERSIONS.TXT](https://github.com/blitz-research/monkey2/blob/develop/VERSIONS.TXT), though I'm not sure why it would use mojo3d/camera!

**Comment by blitz-research** [comment]
Try again now...

> though I'm not sure why it would use mojo3d/camera!

So you can open 3d models in ted2go!

**Comment by DruggedBunny** [comment]
Ahhh... never done that! Thanks, got three days off after today so will be playing from tonight...
