### ISSUE TITLE
Endless "set root folder" loop

### ISSUE THREAD

**Issue by DruggedBunny** [engor/Ted2Go#106]
I get this in the latest Ted2Go dev branch, with latest mx2 develop:

```
Initializing

Monkey2 root directory isn't set.
To continue, you should to specify it.

[OK]   [Cancel]

```
If I choose my folder (same path I've been using all along), it just keeps repeating this until I click Cancel.

It happens whether I run from Monkey2 (Windows).exe or via file double-click, which I have set to the Ted2 binary.

Tiny grammatical error in that dialog, BTW:

> To continue, you should **to** specify it.

Should just read...

> To continue, you should specify it.

**Comment by engor** [comment]
There are no recent changes related to root dir choosing.
Is your ted.exe is inside of monkey2 folder?
Or is your choosed folder is root of monkey2?

Thanks for gram. error.

**Comment by DruggedBunny** [comment]
Just treat this as "one of those weird errors" -- I re-checked out and rebuilt and all is OK!
