### ISSUE TITLE
Block tab?

### ISSUE THREAD

**Issue by blitz-research** [engor/Ted2Go#11]
Block tab still seems to be acting weird to me - it's always tabbing an extra line, eg: if I select the middle 3 lines of:

Function Main()
   New AppInstance
   New MyWindow
   App.Run()
End

...and hit tab, the 'End' line moves across too,

This doesn't happen in notepad++, android studio or 'plain' TextView (haven't tried any others...).

Check out TextView code for how I think it should work - this has been 'fixed' from an earlier version that was not 'notepad++ compatible'.

**Comment by engor** [comment]
When you selected 3 lines cursor is blinking just before End word or in the end of Run() ?

**Comment by engor** [comment]
Fixed, please try it. :)
