### ISSUE TITLE
F1 help broken?

### ISSUE THREAD

**Issue by blitz-research** [engor/Ted2Go#113]
F1 doesn't seem to open help any more - it appears to jump to decl.

**Comment by engor** [comment]
Hm, it tried v2.8.1 (dev) and it works.
Show me Recti and JsonObject, for example.
Do you have prebuilded docs? Maybe rebuilding docs fix that.

**Comment by blitz-research** [comment]
Actually, seems to be going today so close it for now and I'll reopen if it
happens again.


On Sun, Feb 18, 2018 at 5:39 PM, Evgeniy Goroshkin <notifications@github.com

**Comment by blitz-research** [comment]
Yikes, happened again.

F1 and F2 do the same thing, ie: take me to definition of a name.

Tried restarting ted2go and it didn't fix it - but a reboot DID fix it!

I have no idea what could cause that...

**Comment by engor** [comment]
It works for a while and then stop to work?
Any idents stop to work?
A few examples of idents?

**Comment by blitz-research** [comment]
Ugh, hard to reproduce. But once it starts happening it keeps happening.

Should F1 *ever* move the cursor? I put a DebugStop() in just before GotoCodePosition in MainWindow.ShowHelp and it is breaking every now and then when I just click around randomly on 
different identifiers.

**Comment by blitz-research** [comment]
Ok, if I double click F1 on a function param, it takes me to the line where the param was declared, ie: the actual 'Function...' line. Very useful but should F1 be doing this? Is this something to do with what's up?

**Comment by engor** [comment]
Will try to fix that.

There is another 'bug' with help - when property name is the same as its type. Jumping to property instead of type.

**Comment by engor** [comment]
Does anyone have conrete examples of incorrect help jumping in current version?

**Comment by engor** [comment]
I recently improved help detection, so close the issue for now.
Be free to reopen if you found any incorrectness again.
