### ISSUE TITLE
Auto-trim lines?

### ISSUE THREAD

**Issue by blitz-research** [engor/Ted2Go#114]
Hi,

How about the option to automatically trim trailing whitespace from lines?

Bye!
Mark

**Comment by engor** [comment]
Hi. 
I like TrimEnd in IDE but when it leaves whitespaced (empty) lines as is.
I already made this as a part of "fix indentation" feature - it's suitable to fix it here.
There are questions:
1. When to trim - on line changed event or on document saving?
2. Should it be UNDO-able or not? (need to look at some other ide)

**Comment by engor** [comment]
Ps. Sometimes I'm thinking about complex undo command - to be able to have more than one text change as a single undo.
I remember such in Qt:
`void QTextCursor::beginEditBlock()` / endEditBlock.

For "fix indent" stuff I simply replace whole text to have single undo - it works well enough here. :)

**Comment by engor** [comment]
Done the first attempt! And maybe it's enough.
Don't trim inside of multiline strings and comments (#rem or single ').
Maybe need to skip strings only, but what if there is a commented multiline string (and we uncomment it someday)? 
I don't want to analyze whole commented block to searching for strings.. :)

**Comment by blitz-research** [comment]
Yikes, you're right there's more to this than meets the eye! So much for a
simple request...

Thanks for giving it a go, just trying out the latest dev branch now...


On Tue, Feb 27, 2018 at 4:20 AM, Evgeniy Goroshkin <notifications@github.com

**Comment by engor** [comment]
Done.
