### ISSUE TITLE
Autocomplete #Rem

### ISSUE THREAD

**Issue by abe-noll** [engor/Ted2Go#117]
Autocomplete for #Rem seems to duplicate the number sign. 

#### Example
```monkey2
#re 
' becomes
##Rem
```

#### Extra Info
- Windows 10
- Week old git build

**Comment by abe-noll** [comment]
@engor looks like this was fixed in the latest release!

**Comment by abe-noll** [comment]
Sorry! Looks like I spoke too soon . . . But I've found the exact case where it happens now:

### Example
```monkey2
#rem 
' becomes (with tab)
##Rem
```

**Comment by engor** [comment]
Yhanks will see one day.. :)

**Comment by engor** [comment]
Should be fixed in dev branch.
