### ISSUE TITLE
Incorrect word spacing on first launch with a non-default font

### ISSUE THREAD

**Issue by secondgeargames** [engor/Ted2Go#119]
If I use any editor font other than the default one, everything looks fine at first, but after I close Ted2Go and reopen it, the text is rendered with more spacing between words. If I close the file and open another one, everything goes back to normal. This happens with RobotoMono Regular and Iosevka Medium fonts. The UI is scaled with Ctrl+.

![before](https://user-images.githubusercontent.com/1726597/37440516-5b4fbace-27d3-11e8-9ea2-6ca879e358b3.png)
![after](https://user-images.githubusercontent.com/1726597/37440520-5ede78d8-27d3-11e8-8994-f6310376b23d.png)
Fonts: 
[fonts.zip](https://github.com/engor/Ted2Go/files/1813756/fonts.zip)

**Comment by secondgeargames** [comment]
Ok, here is the root of the problem:
1. `mojox.TextView` stores a reference to `RenderStyle.Font` as `_font`.
2. `_font` is updated in `TextView.OnValidateStyle()`
3. You set custom font in `CodeDocumentView.UpdateThemeColors()` as `RenderStyle.Font=newFont`
4. `RenderStyle` getter triggers `TextView.OnValidateStyle()`, at which point `RenderStyle.Font` is not assigned yet.
5. There is no other call to `TextView.OnValidateStyle()` before the document words are measured, which means the words are measured using `_font` from the theme, instead of the font from the settings (Prefs). This leads, in my case, to extra spacing after each word, because my custom font is much more compact than the one in the theme.

**Possible solution:**
Add `OnValidateStyle()` after `RenderStyle.Font=newFont` in `CodeDocumentView.UpdateThemeColors()`

**Comment by engor** [comment]
Please, try latest dev branch.
