### ISSUE TITLE
c++ preprocessor symbols tokenized...

### ISSUE THREAD

**Issue by blitz-research** [engor/Ted2Go#121]
Hi,

I can't use #if, #else etc in c++ as ted2go is capitalizing the words!

Bye,
Mark

**Comment by engor** [comment]
Hi.
Just pushed fix into dev.

c++ directives added:
`#if, #end, #endif, #else, #elif, #define, #undef, #ifdef, #ifndef`

**Comment by blitz-research** [comment]
Thanks!

On Tue, Mar 20, 2018 at 5:19 PM, Evgeniy Goroshkin <notifications@github.com
