### ISSUE TITLE
Folding issues...

### ISSUE THREAD

**Issue by blitz-research** [engor/Ted2Go#124]
Ok, first folding issues - fold the following code:
```
Class C 
   Field x:Int
   Field y:Int
End
```
Then place the cursor at start of the 'Class C' line and hit enter. I end up with:
```
Class C
   Field x:Int
```
It looks like it's showing the first 2 lines of a folded block instead of 1 after you hit enter. If I then hit backspace the ghosted '1 lines(s)...' prints at start of 'Class...' line.

If I hit backspace/enter/backspace/enter etc #lines goes 4,3,2,1 etc. The lines  are still there, and if I unfold/refold #lines goes back to normal.

Actually best way to see all this in action is to stick cursor at start of 'Class...' line and just hit enter/backspace randomly a bunch of times...

But getting there!

**Comment by engor** [comment]
Thanks, will see.
When I announced folding in discord channel I also wrote about such issue.
But it's better to have issue here not only in mind. :)

**Comment by engor** [comment]
I made some tweaks in `folding-fixes` branch.
If it fix this issue (and don't introduce other ones) then we can merge it into master.
