### ISSUE TITLE
Folding shortcuts not working on MacOS + suggestions

### ISSUE THREAD

**Issue by DoctorWhoof** [engor/Ted2Go#126]
The (awesome) code folding is unfortunately not working as desired on MacOS due to the shortcuts being used to type special characters (Like ≠, ±, etc.). The shortcuts actually work... but they type the special characters as well!

Suggestions (similar to what Sublime text uses):
Fold current: Command + [
Unfold current: Command + ]
Fold current and parents: Command + Alt + [
Unfold current and parents: Command + Alt + ]
Fold All: Command + Shift + [
Unfold All: Command + Shift + ]

**Comment by engor** [comment]
Thanks, will fix. `Command` is `Menu` in monkey2? I always forget it.

**Comment by DoctorWhoof** [comment]
I think it's Key.LeftGui and Key.RightGui (supporting both sides would be nice)

**Comment by engor** [comment]
Pushed changes into dev. Please, try it out.
I changed shortcuts for windows too.
The same but `Gui` for macos and `Control` for windows.
