### ISSUE TITLE
ted2go always adds .monkey2 extension

### ISSUE THREAD

**Issue by blitz-research** [engor/Ted2Go#127]
Hi,

I just went to rename a .glsl file to something different and it appears that ted2go is always appending .monkey2 to filenames for 'save as' even if a file already has an extension.

For example,  if I have an open document called 'textured.glsl' and select 'save as...' I am prompted to save it as 'textured.glsl.monkey2'. Even removing the .monkey2 in the filerequester doesn't work - file is still saved as 'textured.glsl.monkey2'.

This seems to be a new problem, pretty sure all this used to work fine.

Bye,
Mark

**Comment by engor** [comment]
Since RequestString () has a default value.. maybe ide shouldn't add ext when create file too?
Just pass .monkey2 as a default.

**Comment by engor** [comment]
It's monkey related bug.
If you choose "Any files" filter in save as dialog - you'll get right your typed extension,
but if you leave default "Monkey2 files" filter then requesters.RequestFile() add .monkey2 even when file already have extension.

**Comment by engor** [comment]
@blitz-research what do you think about the message above?
