### ISSUE TITLE
Folding bug

### ISSUE THREAD

**Issue by DruggedBunny** [engor/Ted2Go#128]
I just ran into a bug where it seems Ted2Go 'thinks' folding is enabled on a function when it's not:

```
#Import "<std>"

Using std..

Function Main ()

	Print "Hi"
	
End

```

If you place the cursor on the empty line before Function, then hit Del (forward-delete), followed by Enter, the text "...4 line(s)" appears next to the function, even though it's not folded.

If you then hit Backspace (backward-delete) with the cursor still before the F in Function, followed by Enter, the Function line vanishes!

Now keep hitting Enter and watch the last few line numbers increase!

Zipped video here shows the above steps, followed by Undo at 15 seconds:

[foldingbug.zip](https://github.com/engor/Ted2Go/files/1957906/foldingbug.zip)

**Comment by blitz-research** [comment]
Happens here too...

**Comment by engor** [comment]
Please, check out dev-branch.
