### ISSUE TITLE
Colorizing .h files

### ISSUE THREAD

**Issue by blitz-research** [engor/Ted2Go#13]
Hi,

Ted2go is colorizing .h files with the mx2 colorizer. Doesn't happen with plain Ted2.

Bye,
Mark

**Comment by engor** [comment]
There are properly c++ keywords for .h, .cpp files.
One obvious bad thing is apostrophe - as it is a comment with current colorizer.
What else?

**Comment by engor** [comment]
Fixed now in dev! :)
A big step to comfort native code editing.
