### ISSUE TITLE
No auto .monkey2 extension?

### ISSUE THREAD

**Issue by blitz-research** [engor/Ted2Go#130]
Hi,

When I create a new file by right clicking a folder in the ted2go project tree and selecting 'new file...', I'm pretty sure ted2go used to automatically add a '.monkey2' extension if you didn't provide any extension.  Otherwise, ted2go would use the extension you provided.

This seems to have changed with the latest dev version. Now, if you don't type an extension it creates an 'extension-less' file. I may be mistaken here, but if not can we have old behaviour back?

Bye,
Mark

**Comment by engor** [comment]
There is a .monkey2 text in requester on show helped you add extension.

What if you really want to create extension-less file?

But no problem to restore old behaviour.

**Comment by engor** [comment]
Fixed.

**Comment by blitz-research** [comment]
> There is a .monkey2 text in requester on show helped you add extension.

Actually, I didn't notice that. I guess I've just been typing the filename
without even looking (which overwrites it).

I'm much cooler with this - put it back if you want.

On Thu, May 3, 2018 at 12:42 PM, Evgeniy Goroshkin <notifications@github.com

**Comment by engor** [comment]
I don't use exception-less files, so .monkey2 is now with us again. :)
