### ISSUE TITLE
mixed indentation corrector destroys code

### ISSUE THREAD

**Issue by abakobo** [engor/Ted2Go#134]
the folowing file is destroyed when click yes on the  "replace with tabs" tabs suggestion. Some Class declaration or End seems to disapear!

(files are in txt format because github refuses .monkey2 extension, just change the extensions)
[box2dted2goBug.txt](https://github.com/engor/Ted2Go/files/2099268/box2dted2goBug.txt)

after indentation replacement:
[box2d_messed-up.txt](https://github.com/engor/Ted2Go/files/2099277/box2d_messed-up.txt)

I've removed the imports so you can see that there is a lot more errors after the indentation replacement process.

Thx for the great work on the IDE

**Comment by engor** [comment]
will see.

**Comment by abakobo** [comment]
I have some simpler files that does it too. Will upload them when I'm back from travel.

**Comment by abakobo** [comment]
[mixed_indent_bug.zip](https://github.com/engor/Ted2Go/files/2122156/mixed_indent_bug.zip)


This one is small enough to fit the small view, there's one line disappearing at the middle of the file, and the next at the end of the file disappears too.

**Comment by abakobo** [comment]
It's looks like it's working ok now..
thx
