### ISSUE TITLE
semanting cpp file?

### ISSUE THREAD

**Issue by blitz-research** [engor/Ted2Go#135]
Hi,

If I have both a .monkey2 file and a .cpp file open but no locked build file, ted2go tries to semant the .cpp file in the backgorund. There are lots of errors!

Bye,
Mark

**Comment by engor** [comment]
will see.

**Comment by blitz-research** [comment]
It also appears to semant monkey2 files if there is no build file/active project - is this a good idea? Should it maybe be optional?

**Comment by blitz-research** [comment]
Ok, might be a bug then. If I close all tabs and then open for example
mx2cc/builder.monkey2 ted2go highlights a ton of errors. These errors
disappear if I open mx2cc and lock it - magic!

I'm loving this whole-project semant thing though. I still don't use
auto-complete much yet, but just seeing all the build errors while I'm
coding is great.

Would it be possible for those little build error popups to open without
having to hover mouse over the correct line (might have to be an option, or
perhaps only auto-show them if all errors are in the same file)? It'd mean
there'd be more than one on screen at a time (or you could even do the
first or last one) but it'd be really cool as it's kind of a PITA to have
to pick up the mouse while your typing away when you can see there's an
error but don't know what it is. Or the error could even appear in the
status bar or something?

Are we still gonna get a 'whole project' tree?!?

**Comment by engor** [comment]
Some fixes pushed into `dev`.
* Disabled parsing of non-.monkey2 files
* Show error message in status bar when you jump to line with error.

Didn't do:
* disable auto-parsing current doc when have no locked file or active project - because it break our app templates.
I think we have to parse current doc and searchin for Main function - if it's here - apply parse result, else - ignore, maybe mark such files as unbuildable.

**Comment by blitz-research** [comment]
> Show error message in status bar when you jump to line with error.

Yes, working nicely!

Ereor message in status bar is not cleared when you fix it but I can live with that.

> disable auto-parsing current doc when have no locked file or active project - because it break our app templates.

How does it break them? App templates are auto-locked when you open them.
