### ISSUE TITLE
console output bug with windows style EOLs

### ISSUE THREAD

**Issue by abakobo** [engor/Ted2Go#136]
I've put this issue in BRL mx2 repo but mark asked me to put the issue here as it appears to be a ted2go bug.

https://github.com/blitz-research/monkey2/issues/394

thx

**Comment by engor** [comment]
\r at the beginning of line means that caret must be moved to start of line erasing last line.
Will make tool-button in output console to disabling it.

**Comment by engor** [comment]
tool-button was added.
