### ISSUE TITLE
Autocomplete issue

### ISSUE THREAD

**Issue by nitrologic** [engor/Ted2Go#14]
When typing Key.Space Ted2Go changes what I type to OnKeyEvent.Space

**Comment by engor** [comment]
When you pressed dot you got insertion of selected item in completion list.
I think to add option in Preferences to disable 'choose by dot'.

**Comment by nitrologic** [comment]
Shouldn't the word Key be in that list and shouldn't it have chosen it as the bast match?

**Comment by engor** [comment]
Yes it should. And I see it right here on the top of completion list.
I suppose, you typed it before parser is completed its _parse-modules_ stage, therefore you didn't see `Key `as a top (best match) item.
