### ISSUE TITLE
Can't drag Docs/Source tabs after recent update

### ISSUE THREAD

**Issue by DruggedBunny** [engor/Ted2Go#140]
Hi Engor,

Did something change with regards to moving Documents or Source tabs within the IDE?

I used to move the docs to the top-right in order to get full vertical height when viewing them, but now I can't drag it any more.

This means documents can only be viewed in the tiny area beneath the source code:

![untitled](https://user-images.githubusercontent.com/1781537/41823863-c679794a-77fe-11e8-9c34-8029466247cb.jpg)

Could this possibly be changed back?

Also, would it be possible to add the language keywords (eg. Local) to the F1 help, so it jumps to the relevant documentation? At the moment it does nothing. Even linking to the Index docs would help.

Many thanks!

**Comment by DruggedBunny** [comment]
Seems to be OK in latest version! Not sure what went wrong as I see no changes...

**Comment by engor** [comment]
Magic detected! :)

**Comment by DruggedBunny** [comment]
Ha ha... yes, it definitely wouldn't drag the tabs at the time I wrote this, I swear!

Forgot about this part when closing topic... what do you think of this?

> Also, would it be possible to add the language keywords (eg. Local) to the F1 help, so it jumps to the relevant documentation? At the moment it does nothing. Even linking to the Index docs would help.

**Comment by engor** [comment]
Don't know. Did you rebuild latest mx2 or it solved by itself?
