### ISSUE TITLE
c/c++ apostrophe handling...

### ISSUE THREAD

**Issue by blitz-research** [engor/Ted2Go#144]
Hi,

It's a minor thing, but the c/c++ parser should ignore apostrophe (single quote) inside of strings. Currently it appears to be toggling 'string mode', eg:

`bbRuntimeError( "Type '"+getName()+"' is not a pointer type" );`

should not be including 'getName()' in the string.

No hurry with this!

Bye!
Mark

**Comment by engor** [comment]
Should be fixed in dev.
