### ISSUE TITLE
Crash with something..Extension?

### ISSUE THREAD

**Issue by blitz-research** [engor/Ted2Go#15]
Hi,

Ok, I can semi-reliably crash ted2go by doing the following:

1) Paste this code into a new document:
```
Class C Extension
	
	Method M()
	End

End
```
2) Delete method 'M' (including the method 'End') so it's just an empty class.

3) Type in the method again - the second char I type here (eg: the 'e' of 'Method' ) causes ted2go to crash.

Seems to only happen with 'Extension' in there. Disabling completion from prefs fixes it.

**Comment by engor** [comment]
Mark, please, check the **ParseInfo** for that test-code by pressing `F11 `and look at `endpos` of method M. 
**Why is it "7:1" ?**
And it doesn't depends on `Extension` keyword.

Hm... All methods have the same behaviour - they have `endpos` equals to {next-method-srcpos minus one} position, but should be equals to nearest `End` keyword.

**Need to fix.**

And the second, for classes with `Extension` keyword there is `superType` section generated by **geninfo**, that contains the same ident name as our class has.
And ted2go fall into endless recursion calls when extracting items for autocompletion.

I've just fixed that in **v2.2.4**  (w/o changing geninfo).
_Pushed to rep._
