### ISSUE TITLE
"Close tab" on Macs got replaced by wrong shortcut

### ISSUE THREAD

**Issue by DoctorWhoof** [engor/Ted2Go#151]
On a recent update, "close tab" was changed from "Cmd+W" (correct) to "Alt+W" (incorrect, since it adds the character "∑" to the document).

Thanks, and special thanks for the incredible work on all the recent updates.

**Comment by DoctorWhoof** [comment]
Actually, close tab should be "Command+W", not "Ctrl+W".
As for select word, I usually just double-click... :-)

**Comment by DoctorWhoof** [comment]
Oops, closed by accident!

**Comment by engor** [comment]
It's not just select word, it's expandable selecting. Try to press ctrl+w few times on idents with dots like `myclass.myprop.mypa|ram - where | is cursor.

**Comment by DoctorWhoof** [comment]
Ctrl+W seems to work fine on MacOS. It's Command+W that disappeared! (it used to work fineto close tabs).

Thanks.

**Comment by engor** [comment]
Ctrl+W restored to close tab (already is in dev branch).
