### ISSUE TITLE
"Examples" tab is not sorted.

### ISSUE THREAD

**Issue by DoctorWhoof** [engor/Ted2Go#152]
On MacOS, the great "Examples" tab is not sorted alphabetically, making it hard to find a specific example.

Thanks!

<img width="390" alt="screen shot 2018-07-22 at 10 11 24 pm" src="https://user-images.githubusercontent.com/6250116/43058393-4d9b0e80-8dfc-11e8-808e-ecb7cdfdf02d.png">

**Comment by engor** [comment]
Seems like sorting works inside these root folders only now. Will see.

**Comment by engor** [comment]
Fixed in dev branch.
