### ISSUE TITLE
Close Project

### ISSUE THREAD

**Issue by Kanati8869** [engor/Ted2Go#154]
I have a few projects listed in the project tab.  I right click and choose "close project".  At this point ted2go locks up.  The application does not go into "not responding", but it will not allow me to do anything else.  I can exit using the X and do not have to terminate the process in task manager.  It did this three times in a row.  When I went to verify that it was still doing it this morning, it did not do it and came up with the dialog box to verify I wanted to close it.  It then proceeded to do just that.  

I believe that there is some circumstance where that dialog either does not get shown and it still continues to wait for it to be clicked...  or it does a "pop behind" or something where the dialog is not accessible and that is what I was experiencing.

I will attempt to reproduce the issue again, but for now it is working as intended I believe.

(Windows 10, Monkey 2018.07)

**Comment by engor** [comment]
Can't reproduce. When you close project IDE ask "really close?" And then close by Yes answer.
If confirm dialog was not shown - this was the reason.

**Comment by Kanati8869** [comment]
dialog was not shown.  I haven't seen the problem since, so I assume you
can close the issue.
