### ISSUE TITLE
AltGr+\ Bug?

### ISSUE THREAD

**Issue by DrCox85** [engor/Ted2Go#155]
When i try to type AltGr+\ the cursor move to the beginning of the Document(Ln:1 Col:1) and Print \.

Monkey2 v2018.07b
Mx2cc v1.1.15
Ted2Go V2.12
Windows 10

**Comment by engor** [comment]
Works fine now?

**Comment by DrCox85** [comment]
Yeah works fine now, with latest dev. :blush:
