### ISSUE TITLE
It would be great if default function/method values where showed when filling params

### ISSUE THREAD

**Issue by abakobo** [engor/Ted2Go#166]
When you declare for example:
```
Function Blah(i:Int=0,j:Int=2)
```
It would be great if the default values where shown when writing the function params. Or at least showing that there is a default value and that we don't have to fill the parameter.

thx

**Comment by engor** [comment]
Nice request, will see.

**Comment by engor** [comment]
Done with 

> Or at least showing that there is a default value and that we don't have to fill the parameter.

for a first try. Available in **dev** branch.

**Comment by abakobo** [comment]
Thanks!
