### ISSUE TITLE
tab mid-line?

### ISSUE THREAD

**Issue by blitz-research** [engor/Ted2Go#2]
I'm a bit surprised I can't use 'tab' in the middle of a line - it just tabs the whole line.

I use this quite a bit when doccing, eg: for tables. 

I would prefer tab had it's old behaviour, but am willing to abide by the needs of power users if necessary! But still, would be nice if there was a way to use tab midline.

**Comment by engor** [comment]
Thanks. Fixed.
Now, if there is no selection - pressing tab just insert \t ; and shift+tab doesn't work in this case.
Also fixed storing of selection range while tabbing.

**Comment by blitz-research** [comment]
Thanks, much better.

I still find tab behavior a bit weird though. I don't really get the idea of tabbing the whole line if any part of it is selected. I guess it doesn't hurt much, as replacing a selection with tab is fairly rare, but neither notepad++ nor visual studio do this.

Also, not sure if this is a bug, but selecting exactly one line and hitting tab causes 2 lines to be indented. Again, this seems to be unique to ted2go, and it makes indenting just 1 line a little counter-intuitive unless you know about 1) above, as you've got to select some - but not all! - of the single line you want to indent.

**Comment by blitz-research** [comment]
...think you might have broken  autocapitalize a bit too with last update. Typing this:

return blah

...no longer capitalizes 'return', ditto 'new blah' etc.

**Comment by engor** [comment]
Ok, I'll fix it ASAP.

**Comment by blitz-research** [comment]
Is autocaps supposed to be fixed in master? Doesn't seem to be here.

**Comment by engor** [comment]
Will be fixed next time. There are two issues in one, and I forgot the second one and close it, but capitalization bug is in my trello list.
