### ISSUE TITLE
Crash on Windows 10

### ISSUE THREAD

**Issue by noroads2015** [engor/Ted2Go#20]
open new file, type
```
Class Something
	Field grid:=New Grid(20,20)
End
```
delete the 20,20.  Type 4, then wait a second or two.
```
Class Something
	Field grid:=New Grid(4,)
End
```
Ted2Go will crash at this point in Windows 10 (don't know about earlier versions or other OS)

**Comment by engor** [comment]
There is something inside of mx2cc that used as code parser.
parser output:
```
Mx2cc version 1.1.04
***** Building app 'C:/proj/monkey2/tmp/_mx2cc_parse_1.monkey2' *****
Parsing...
Caught signal:Memory access violation
```

**Comment by engor** [comment]
Fixed in dev branch.
I hope this fix cover many crashes.
