### ISSUE TITLE
Auto capitalizing code in comments?

### ISSUE THREAD

**Issue by blitz-research** [engor/Ted2Go#21]
Ted2go appears to be auto capitalizing stuff in #rem comments, eg:

#rem monkeydoc hex string

Capitalizes 'hex' and 'string' here.

**Comment by engor** [comment]
I tried to type that and it didn't capitalize.
But it show completion list and you can choose capitalized variant from there.
Do you mean completion list or manually typed words?

**Comment by engor** [comment]
I did understand! 
Mark, you need to disable "Choose by Space" option in prefs.
![2017-05-25_11-37-12](https://cloud.githubusercontent.com/assets/5233803/26436146/9d07ceba-413e-11e7-9dd6-8d233413ab21.png)

**Comment by blitz-research** [comment]
Seems to have done the trick, thanks.

Just updated to the latest github master - preferences looks nicer and I
love the '...' between lines numbers!



On Thu, May 25, 2017 at 4:38 PM, Evgeniy Goroshkin <notifications@github.com

**Comment by blitz-research** [comment]
ooer, status bar at the bottom looks cool too!

**Comment by engor** [comment]
Thanks, I glad to hear that! :)
So, I close this issue.
