### ISSUE TITLE
A few issues...

### ISSUE THREAD

**Issue by blitz-research** [engor/Ted2Go#23]
Hi,

Possibly something I'm doing but...

1) The bottom 'output' view seems to close itself when I build/run, and I have to hit 'ESC' to open it again to view program output. Actually, it does seem to open itself, but then closes when app ends. Could this be made optional?

2) Autocomplete seems to close itself when I type '(' - is this normal?

**Comment by engor** [comment]
Hi. 
1. Consoles doc store visibility state that it has when you run/build/semant and restore it after process finished. If you change visibility between that you get unexpected state. 
So, need to disable restoring if user change state by himself (added to _todo_).
2. Yes, it's normal. The logic here is:
`if EventType.KeyChar and Not IsIdent() Then Hide()`

**Comment by engor** [comment]
I added in 'dev' disabling restore console's visibility if you change it yourself after build started.
