### ISSUE TITLE
Crash!

### ISSUE THREAD

**Issue by blitz-research** [engor/Ted2Go#24]
Hi,

I can reliably crash ted2go by type this into a new empty file:

```
Class Test
	Method New()
		Super.
```

As soon as I hit the dot after typing super, kablam! Ted2go just exits.

Bye!
Mark

**Comment by engor** [comment]
Hi. I just tried that and didn't get a crash. Hmm.
Is that happen in the letest version from github?

**Comment by blitz-research** [comment]
Dunno about the very latest, pretty recent.

Will update you when I get to try the latest.

Actually, just tried it with release v1.1.04 and it happens there too.

**Comment by nitrologic** [comment]
does it for me too, on develop branch, turning off auto complete fixes it.

and I can't turn off auto indent...

**Comment by blitz-research** [comment]
This is still happening, but is proving very hard to reproduce in debug mode!

**Comment by blitz-research** [comment]
Chaning line 487 in Monkey2Parser (sort of) fixes it for me:

			If scope item=scope.NearestClassScope

I have a feeling there may be a few more Null Selfs in there, and the optimizer is confusing the hell out of things and making release behave VERY differently so I think I will be adding the Self=Null check very soon!

**Comment by engor** [comment]
> Chaning line 487 in Monkey2Parser (sort of) fixes it for me
Thanks!

I want to continue parser improvements _at one point_. 
There are a lot of things to make our IDE super cool! :)

**Comment by blitz-research** [comment]
IDE is already super cool, but any additions welcome!

Can you change above line in master ASAP?

On Wed, Jun 28, 2017 at 5:03 PM, Evgeniy Goroshkin <notifications@github.com

**Comment by engor** [comment]
> Can you change above line in master ASAP?

Done.

**Comment by blitz-research** [comment]
Cheers!


On Thu, Jun 29, 2017 at 1:12 PM, Evgeniy Goroshkin <notifications@github.com
