### ISSUE TITLE
capitalizing in comments.

### ISSUE THREAD

**Issue by blitz-research** [engor/Ted2Go#26]
Hi,

Still having problems with stuff capitalizing in comments - means I can't write any docs.

Bye,
Mark

**Comment by blitz-research** [comment]
Ok, I had the 'choose by space' option enabled, but I'm struggling to see the point of capitalizing in comments in the first place. But as long as I can turn it off...

**Comment by engor** [comment]
I'll see it. It's time to improve parser too.
