### ISSUE TITLE
unable to build on develop branch ( Linux )

### ISSUE THREAD

**Issue by nitrologic** [engor/Ted2Go#27]
From git clone of monkey2 develop branch ted2go build is broken.

The script expects ted2.monkey2 NOT Ted2.monkey2 perhaps?

Launcher expects binary to be called ted2 NOT Ted2 also.

**Comment by nitrologic** [comment]
after renaming back to ted2.monkey2 I get following which may be monkey2 linux issue perhaps 

> /home/trv/github/blitz-research/monkey2/src/ted2go/ted2.buildv1.1.05/linux_release/build/_1src_2ted2_0ted2.cpp.o: In function `g_ted2go_SetupMonkeyRootPath(bbString, bool)':
> ted2_ted2.cpp:(.text+0x49e): undefined reference to `bbRequesters::Confirm(bbString, bbString, bool)'
> ted2_ted2.cpp:(.text+0x73f): undefined reference to `bbRequesters::Notify(bbString, bbString, bool)'
>

**Comment by engor** [comment]
Sorry for delay.
Linux is case-sensitive. 
AFAIK Mark fixed launcher for Linux.
