### ISSUE TITLE
Can't "Save As" on MacOS

### ISSUE THREAD

**Issue by DoctorWhoof** [engor/Ted2Go#32]
After I create a new tab and type some code, I can't save the new file because the  "save" button is greyed out. Same thing if I go into an existing file and try "Save As".

Saving over existing files works fine, but I can't make new files through Ted2Go.
(Workaround: create an empty file outside Ted2Go with the correct name, then open it in Ted2Go)

I would tell you which version I'm using, but the "About" dialogue doesn't tell me. I downloaded it last week from Itch.io.

**Comment by engor** [comment]
Version shown in window title, for example: Ted2Go v2.3.2.

> "save" button is greyed out
Whole menu item text is gray or shortcut text only?
Shortcuts have it's own text color.

I just tried version from itch.io (2.3.2) and all work fine there.

- I pressed `Cmd+T`   ->  got new untitled document.
- I pressed `Cmd+S` for it   ->  I see Save-As dialog.
- I pressed by mouse File -- Save As...   ->  see dialog too.
- I press right mouse button in project folder and choose menu item 'New file'   -> file was created successfully.

* I run Ted2Go from Downloads folder.

**Comment by DoctorWhoof** [comment]
Ok, I'm on 2.3.2, using MacOS Sierra 10.12.5.
Running Ted2Go from a folder under Applications. Maybe it's a permission thing? 

Save button is definitely disabled in the save dialogue.
<img width="832" alt="screen shot 2017-06-23 at 12 28 41 am" src="https://user-images.githubusercontent.com/6250116/27471059-4b6ac0ca-57ab-11e7-9969-d3a07b4e1db6.png">

**Comment by engor** [comment]
146% that's permission thing. :)

**Comment by DoctorWhoof** [comment]
I tried the ted2_macos that comes with Monkey2, v2.2.3, and that one works fine running from the same folder.

**Comment by nitrologic** [comment]
I would regards this is a Ted2Go issue. Save should default to a writable folder like Home or Desktop NOT inside  installation folder for sake of user friendly.

**Comment by DoctorWhoof** [comment]
I don't think the folder is the problem. It's greyed out anywhere, including if I try saving on my own home folder.

**Comment by nitrologic** [comment]
Hmm, I suspect unless the itch version has been signed you may be out of luck.

I only build from source and have never seen this.

**Comment by engor** [comment]
Open/Save requesters is a part of mx2 core, I don't know what inside and why them don't work. :)

**Comment by nitrologic** [comment]
Heh, yes ignore my comment.

**Comment by engor** [comment]
> Save New and Save As could default to a writable folder like Home or Desktop NOT inside installation folder, it would be more user friendly.

I agree.

**Comment by DoctorWhoof** [comment]
Tried building from source (2.3.2), same problem. Is there a MacOS preference somewhere that could be affecting this? It only happens in Ted2Go, though, so I don't think that's the case.

I actually don't think it's a permissions thing either, because I can create new folders from the save dialogue without problems. It seem more likely to be a UI thing.

**Comment by engor** [comment]
Is it solved or not?

**Comment by DoctorWhoof** [comment]
Solved in 2.5 (I think it's been solved since at least 2.4). Thanks!
