### ISSUE TITLE
Ted2Go closes unexpectedly

### ISSUE THREAD

**Issue by noroads2015** [engor/Ted2Go#34]
Open Ted2Go.  Type "Self." without the quotes.  When you press the . the IDE closes.  Only happens when autocomplete is enabled.

**Comment by engor** [comment]
I can't reproduce.
Please, rebuild version from DEV branch and try in it.
Possibly, fixed.

**Comment by noroads2015** [comment]
Tried the dev version (4.0) same problem.HP 15 laptop amd a8 6410. Windows 10 creators edition 4gig ram. Compiled with m2 1.1.4

**Comment by noroads2015** [comment]
Odd, I would've sworn that I had updated to the latest dev version.  After reading on the MX2 site of someone else having the same problem, then fixing it with the dev version, I decided to try again.  Now everything seems to work fine.

**Comment by engor** [comment]
Nice.
