### ISSUE TITLE
rebuilding ted2go takes hours.

### ISSUE THREAD

**Issue by Pakz001** [engor/Ted2Go#35]
I am wondering if it is normal for my computer to take hours to rebuild the ted2go? I downloaded the dev package and put it in the sr ted2go folder and ran the script rebuildted2go.

It normally also takes quite a long time but now it is been going for 2 hours already and is still showing compiling.

**Comment by coconcode** [comment]
1) What is your CPU? For me takes a few minutes with an i5 2320.

2) You might check the CPU activity, is it idling or working? Idle activity might means that something is broken. Might be a bug...

3) For doing a rebuild, I would recommend it the changes are small and well known, specifically when you edit the modules yourself and you can control the changes. Most of the times pulling changes might involve lots of changes from lots of modules and would makes things more complicated. Though I am sure that the c++ compiler has a way to figure things out, but you never know.

4) Also for doing the compilation you might run the bat file from the command prompt and do a piping into a text file like this: rebuildted2go.bat > report.txt

I don't know if any of these helps but it might worth to mention it.

**Comment by Pakz001** [comment]
I am using a amd a8(laptop). There was mostly no cpu activity.  I had the regular dev package that I was rebuilding. I will try the >report.txt

**Comment by Pakz001** [comment]
I broke of the older compiling after opening up the laptop. I gave it a ctrl+c and it went and finished the job. I did another bat and put the >error.txt behind it. 
I kept checking the error.txt. After a number of minutes inside it it showed it was finished but the cmd console showed nothing. I then broke it off again.

**Comment by blitz-research** [comment]
You could try manually entering the commands in rebuildted2go.bat (I assume
you're on windows?) and see where it gets stuck.

It certainly shouldn't take hours to build! Worse case here is about a
minute.

**Comment by Pakz001** [comment]
I tried entering it line by line. It went allright. took less then 10 minutes for everything to complete. Then I ran the bat again and this went allright also. Also less then 10 minutes. 

Yesterday it got stuck twice. I did see the windows virus package in the background being active at top of the cpu usage this time. Maybe that was doing something? I have no idea why it went so difficult yesterday.

**Comment by coconcode** [comment]
Last chance to get it is to use the  "Process Monitor" by SysInternals and try to filter the mxcc or perhaps the g++. This technique is experimental, I don't know if leads to a clue, but it would worth trying out. The point would be to see what the g++ compiler is reporting if possible.

Note: Do you think that the mxcc might need an additional option to provide output from the g++ operations as well? This would be handy for cases such these.

**Comment by blitz-research** [comment]
You can pass '-verbose=1/2/3' to mx2cc for more verbose output. To dump to
console, edit the .bat/.sh files to redirect/print output. Personally, I
don't like having too much text spewing to the console when building
though...

But this sounds a bit like a one off thing - has it happened again?
