### ISSUE TITLE
Eating my Main()!

### ISSUE THREAD

**Issue by blitz-research** [engor/Ted2Go#4]
Hi,

Thanks for the atuo-caps fix, but now, if I type 'Function Main()' the 'Main' disappears and I'm left with 'Function ()'!

Happens whether or not I autocomplete with tab.

Is this happening to you?

**Comment by engor** [comment]
Oh sorry. Latest version eat any words except of keywords.
if you type 'function abc' and press enter - 'abc' will be aeten.
Just pushed fix for that.

**Comment by blitz-research** [comment]
> Latest version eat any words except of keywords.

Might wanna make that optional!



On Fri, Nov 25, 2016 at 5:33 PM, Evgeniy Goroshkin <notifications@github.com

**Comment by engor** [comment]
No, it was a bug and I fixed it. :)
"Latest version" from comment above is now "previous" after I pushed bugfix.

**Comment by blitz-research** [comment]
...still seems to be happening here with the latest master. I can see the
fix in the commit history though.



On Fri, Nov 25, 2016 at 5:58 PM, Evgeniy Goroshkin <notifications@github.com

**Comment by engor** [comment]
How it's possible... I run new sources and there is no bug.
I typed 'Function ma' then autocompletion opened, I choosen 'Main()' here and press Tab.
I got 'Function Main' and added brackets and press Enter. There is nothing eaten.

**Comment by blitz-research** [comment]
Must be something I'm doing, as I download a zip of main branch and tried it with 1.1.01 release and it worked.

Possibly something to do with my lack of understanding of submodules - everything looks all right there but it's obviously not!

**Comment by blitz-research** [comment]
Found it! I bumped mx2_version yesterday but forgot to bump the version dirs in the build scripts.
