### ISSUE TITLE
'find' going out of sync.

### ISSUE THREAD

**Issue by blitz-research** [engor/Ted2Go#44]
Hi,

Something's weird about 'Find'. For example, if you enter this into a new file:

```
this is a test

this is a test
```

Then find the first 'this', esc out of find requester, delete last 's' of 'this', hit F3 to find again, the next find result is off by one charatcer, as if it was searching the document as it was before the edit.

This accumulates too, so F3 for finding stuff is messy if you're editting lots as you go.

**Comment by blitz-research** [comment]
Also, 'Find Next' doesn't start at the current cursor Location. Pretty sure evey IDE/teditor I've ever used looks for 'Find Next' text starting at the current cursor location.

**Comment by engor** [comment]
Fixed in 'dev'. Please, try it and let me know is it correct now.

**Comment by blitz-research** [comment]
Still not fixed - if replace text is different length from find text, then when you click 'replace' on find dialog, it replaces the find text but then when it automatically does find next, the found selection is off by some amount (looks like the difference between find text length and replace text length).

I had a look at OnFindNext but that's unrecognizable now!

**Comment by blitz-research** [comment]
The code appears to be using the same set of results for each 'find next'. This will however be incorrect once a replace occurs.

**Comment by engor** [comment]
Hm, in my latest changes about search I listen to doc.TextChanged and reset results if theare are changes.
I try to replace text and it works correctly.

But I made a fix for Replace action after posting here to you. And maybe you was so fast to grab changes w/o replace fix?

'Entire solution' is good option - just need to full testing and fixing that. :)
