### ISSUE TITLE
MacOS shortcut mixup

### ISSUE THREAD

**Issue by DoctorWhoof** [engor/Ted2Go#47]
Hey Nerobot, BIG thanks for implementing the "jump to previous/next word" shortcuts on MacOS!

However, they're assigned to "Command+Left" and "Command+Right", instead of "Alt+Left" and "Alt+Right".

The actions previously assigned to Command+Left/Right (Jump to beginning/end of line), which were correct before, are now replaced by Jump to Previous/Next.

Sorry if my request wasn't clear before!

**Comment by engor** [comment]
Oh, I will see.
But I didn't change jumping t words, probably Mark done that..

Please explain me again :) - what to do.
" Revert Cmd+Left/Right to jump at start and end of like (that was replaced with Alt) "
right?

And what about Alt+Up/Down - are they incorrect and need to return to Cmd too?

**Comment by DoctorWhoof** [comment]
These are the standard shortcuts for text editing, by Apple. It's what we should match:
```
Command–Up Arrow | Move the insertion point to the beginning of the document.
Command–Down Arrow | Move the insertion point to the end of the document.
Command–Left Arrow | Move the insertion point to the beginning of the current line.
Command–Right Arrow | Move the insertion point to the end of the current line.
Option–Left Arrow | Move the insertion point to the beginning of the previous word.
Option–Right Arrow | Move the insertion point to the end of the next word.
Shift–Command–Up Arrow | Select the text between the insertion point and the beginning of the document.
Shift–Command–Down Arrow | Select the text between the insertion point and the end of the document.
Shift–Command–Left Arrow | Select the text between the insertion point and the beginning of the current line.
Shift–Command–Right Arrow | Select the text between the insertion point and the end of the current line.
Shift–Up Arrow | Extend text selection to the nearest character at the same horizontal location on the line above.
Shift–Down Arrow | Extend text selection to the nearest character at the same horizontal location on the line below.
Shift–Left Arrow | Extend text selection one character to the left.
Shift–Right Arrow | Extend text selection one character to the right.
Option–Shift–Up Arrow | Extend text selection to the beginning of the current paragraph, then to the beginning of the following paragraph if pressed again.
Option–Shift–Down Arrow | Extend text selection to the end of the current paragraph, then to the end of the following paragraph if pressed again.
Option–Shift–Left Arrow | Extend text selection to the beginning of the current word, then to the beginning of the following word if pressed again.
Option–Shift–Right Arrow | Extend text selection to the end of the current word, then to the end of the following word if pressed again.
```
You can find the complete list here: https://support.apple.com/en-us/HT201236

**Comment by engor** [comment]
As I can see, I need to revert my latest shortcut changes and all became OK. :)
Tx!

**Comment by engor** [comment]
Would you build from sources or will wait for binaries?

**Comment by DoctorWhoof** [comment]
I can build from source, thanks!

**Comment by blitz-research** [comment]
Woah, just tried to use Ted2go on macos and yes, shortcuts are badly broken!

Can you push fixed master ASAP!

**Comment by engor** [comment]
Pushed in dev. In master all is ok here.

**Comment by blitz-research** [comment]
Whew, so macos 1.1.07 isn't broken then?


On Sat, Sep 16, 2017 at 6:22 PM, Evgeniy Goroshkin <notifications@github.com

**Comment by engor** [comment]
I suppose it's OK. :) 
I'm working in dev branch until release (except of important fixes).

**Comment by DoctorWhoof** [comment]
Now Command+Cursors are restored, but Alt+Cursors still doesn't exist!
;-P

If you tell me where to change it I can give it a try and make a pull request,  but Ted2Go's code is very intimidating to me!

**Comment by engor** [comment]
@DoctorWhoof Try dev branch now. Alt+Left / Right were assigned for navigate prev / next. I changed them to Alt+Ctrl+Left/Right
