### ISSUE TITLE
Auto kill running app?

### ISSUE THREAD

**Issue by blitz-research** [engor/Ted2Go#49]
Not sure if this is new, but if I get a runtime error in debug mode, and try to build/run  again without first manually stopping app in debugger, I get permission denied with the exe. I have to manually click stop button on debugger to prevent this.

I don't remember this happening in older versions - didn't it used to nuke the app for you?

**Comment by engor** [comment]
It's an old issue. (Along with crashing app if close it right after run).
Any ideas how to fix? I need to catch errors, but how?
Not often, but I have to stop "mx2cc_windows.exe" to solve that.

**Comment by engor** [comment]
I copy-pasted this logic to ted2go. :)

**Comment by blitz-research** [comment]
As for app exit, how about having a global stack of all currently running
'parsing' procs? When a proc finishes via the Finished signal, it just
removes itself from the stack. Should be no sync issues thanks to fibers.
Then at app exit, go through the stack and Terminate all procs. Terminate
is safe to use redundantly, ie: it shouldn't matter if you terminate a
terminated app etc (in theory).

**Comment by blitz-research** [comment]
Maybe this should be built in to Process class? Or opt in?

**Comment by engor** [comment]
I have ProcessReader class especially for monitoring and batch kill processes.
I am debugging this moment right now - app crashes when I call StopAll().
Modules parsing processes starts inside of a fiber.
Opened docs parsing starts inside of timer.
I terminate-all in main fiber (window cross button pressed).
Also I tried to wrap it into fiber and waiting a future - no luck.

As a variant - waiting for currently started processes and then close.
But I want to understand - what's wrong with proc.Terminate.

**Comment by engor** [comment]
Hm. Inside of ProcessReader I am waiting a future. I pass value to future in Stop() method but no luck too.

**Comment by engor** [comment]
Look at MainWindow.Terminate () if you going to debug. I can continue later.

**Comment by engor** [comment]
VS Debugger said me: `Unhandled exception at 0x7484F828 (kernel32.dll) in ted2.exe: 0xC0000005: Access violation writing location 0x0C25FF64.`
Right on `_process.Terminate()`. But it's a randomly process instance.

I tried to create new process for any operation (don't reuse existing) and I got MAV-exception at `Local code:=_process.ExitCode` - but `_process` isn't null here.

Also I tried to call `_process.Terminate()` after it finished and have no output but this cause crash app.

**Comment by blitz-research** [comment]
Can you try and duplicate with a small test program, say, something that
just starts mx2cc compiling something then calls libc.exit_(0) or something?


On Mon, Sep 25, 2017 at 7:55 PM, Evgeniy Goroshkin <notifications@github.com

**Comment by engor** [comment]
I tried separate small program but can't catch crash on it.
As a result - I implemented waiting for normally process finished behaviour.
We can see a few secs freeze after closing app instead of crash.
Most users will not see it, I hope. :)

**Comment by engor** [comment]
```
Function WaitingForStopAll( wait:Future<Bool> )
	
	_stopSize=0
	_stopCounter=0
	
	For Local r:=Eachin _items
		If r.IsRunning
			_stopSize+=1
			r.Finished+=Lambda( s:String,c:Int )
				_stopCounter+=1 ' * finished can be executed while we inside of loop 
				If _stopCounter=_stopSize Then wait.Set( True )
			End
		Endif
	Next
	If _stopSize=0
		wait.Set( True )
		Return
	Endif
End
```
* I think possibility of getting Finishid signal right inside of loop is like zero.
or not?
Don't know how to solve it better way.
This way worked well. :)
