### ISSUE TITLE
The editor crashes if a variable declaration contains a string-literal with the back-slash character

### ISSUE THREAD

**Issue by ImmutableOctet** [engor/Ted2Go#5]
The title pretty much says it all. Try declaring a variable of 'String' and assign it to a string literal with the **\\** character.

```
Global x:String = "\"

Function Main:Void()
End
```

This crashes the editor when background-compiling, and I'm not sure why.

**Comment by engor** [comment]
There are something wrong with Json parser. 
In our case we have "toke":"\". This produced null-result for jsonObject.

**Comment by engor** [comment]
Already fixed in monkey2 develop branch.
You should at least to grab new mx2cc binary.
