### ISSUE TITLE
Esc key stops working.

### ISSUE THREAD

**Issue by blitz-research** [engor/Ted2Go#50]
For some reason, the 'Esc' key stops working after a while ( about 10 mins?) - ie: it no longer toggles consoles/find. Restarting IDE fixes it.

**Comment by engor** [comment]
Maybe, something happen with sdl_events?

**Comment by blitz-research** [comment]
Seems to happen reliably after updating modules.

**Comment by blitz-research** [comment]
Try removing line 108 of UpdateModulesDialog: actCancel.HotKey=Key.Escape.

This is probably not getting removed when dialog is closed (hotkey handling
is pretty basic) and 'eating' the main esc handler.

You don't need this anyway as you're already using Dialog.SetKeyAction
which is the right way to do this!
