### ISSUE TITLE
Crashing a lot...

### ISSUE THREAD

**Issue by blitz-research** [engor/Ted2Go#52]
Hi,

I am finding the IDE is still crashing a lot - no error, just a sudden exit.

HJave just upgraded to dev version and same thing happening.

Seems to be mostly when I'm typing, Think it may be autocomplete related, will keeping playing...

Bye,
Mark

**Comment by engor** [comment]
Can you debug it?

**Comment by blitz-research** [comment]
Ok, it seems to be corrupting something as I'm getting weird crashes everywhere.

I did however get a crash at one point in CheckUsingsFilter in Monkey2Parser.monkey2 which is new code?

Gonna have to turn off autocomplete for a while now so I can do some coding! Will have another look later...

**Comment by blitz-research** [comment]
It may not be autocomplete as I turned that off and it still crashes a lot. In particular, the file I've been attempting to edit is canvas.monkey2 which seems to be super susceptible to crashes.

I've ended up reverting to 1.1.07 ted2go src and no crashes so far even with atuocomplete on.

**Comment by DoctorWhoof** [comment]
May not be related, but I used to get a lot of crashes when "Show inherited members" was on in the Source panel. Have been keeping it off since then, so I can't say for sure it still happens.

**Comment by engor** [comment]
Thanks, guys! I will see.

**Comment by engor** [comment]
After some researching.
1. I got crash almost for any words typing / chars removing inside of `Canvas `class.
see at picture
![2017-10-05_11-44-00](https://user-images.githubusercontent.com/5233803/31211625-d1b57de4-a9c4-11e7-8c18-2369a142e480.png)

2. After rework `timer-for-parser` in CodeDocument, I started to get crash at `CodeDocument.UpdateCodeTree()`, in `SortItems()` debugger stopped at for.. each line in `CodeItem` class here:
```
Property ParamsStr:String()

	Local params:=_params
	If Not params Return Null
	If _paramsStr Return _paramsStr

	Print "_params.Length: "+params.Length+" "+Ident
	_paramsStr=""
	For Local p:=Eachin params  ' !! DEBUG STOP, BUT params.Length == 1
		If _paramsStr<>"" Then _paramsStr+=","
		_paramsStr+=p.ToString()
	Next
	Return _paramsStr
End
```
**Parser completed work  in this case.**
I had no luck with attemp to use `App.Idle+=UpdateCodeTree`.

3.  After commenting `CodeDocument.UpdateCodeTree()` calls I started to get debugstop line as in item 1 above.
Parser didn't complete work  in this case, **crash inside of process**.
Sometimes completed sometime not, why!

How UpdateCodeTree() can affect on parsing process?? Don't know.

Any ideas?

**Comment by blitz-research** [comment]
I recommend removing stuff until it works reliably, then adding it back
piece by piece. If you don't start any mx2cc's does it work? If you start
them but ignore output does it work OK? etc. etc...

It may be that mx2cc is crashing, but IDE should really handle that? I
might add a mode that shows crashes in a messagebox or something.

**Comment by blitz-research** [comment]
Just opening PromptInvasion is causing many crashes for me!

**Comment by blitz-research** [comment]
Try removing the _stdoutWaiting=null just immediately after the
_stdoutWaiting.Set() in processreader.

This solves at least the promptinvasion crashes for me. I tried using
Console instead of ProcessReader and this also solves the promptinvasion
crash, although there's no obvious reason why as ProcessReader is very
similar to Console - except that futures *aren't* nulled after being set.

Not sure what's going on here, but by setting _stdoutwaiting to null just
after the Set(), there may be nothing keeping the futue object alive GC
wise, and it may be being collected. The other fiber should in the middle
of its 'Get()' at the time, so needs to be kept alive as it has to return
it's set value!

More research required...

**Comment by blitz-research** [comment]
Also, you should really check for JsonObject.Parse() returning a null
object in Monkey2Parser, in case mx2cc crashed or stdout was somehow
mangled.

**Comment by engor** [comment]
Thank you very much, Mark!
It also solved broken obtain/recycle logic in ProcessReader.

**Comment by blitz-research** [comment]
Yeah, seems to have done the trick, been using ted2go all day without a
crash. Not totally sure what's going on but I have some ideas...

BTW, what exactly is the point of the process recycler? It'll be saving
very, very little overhead, if any. By far the biggest overhead with
ProcessReader will be Process.Start(), which actually creates/starts an OS
process, and which has to be done whether the  ProcessReader 'wrapper' is
recylced or not. The overhead of this is likely to be much, much greater
than the overhead of creating new ProcessReader objects and the related GC.
Or is there some other reasons for the recycler?

**Comment by engor** [comment]
> Or is there some other reasons for the recycler?
No other reasons. :) Just to decrease new objects creation.

**Comment by blitz-research** [comment]
I would guess it's actually slower - but the only way to know for sure
would be to empirically test it.

'New' uses a very fast recycling allocater for objects <256 bytes large, so
as long as your ctor is simple, New is basically 'free'.

However, your recycle stack will mean you are keeping dead/unused objects
alive for longer that is really necessary (you don't null out _process
either so that will remain alive for longer too). This will incur a little
more GC work as GC will have to visit each item on the stack to mark it as
alive.

You still want them in a global stack so you can terminate them at exit,
but you ideally want to remove them from the stack as soon as their
finished IMO. I hacked up a little system like this using Console while
finding the problem and it worked fine and was very simple.

Sheesh, I go to all the effort of writing this cool stuff and everyone
works around it...

Ok, will stop bugging you about the recycler now - promise!

**Comment by engor** [comment]
Small profit, so I almost removed recycling. :)

And... looks like now I can just call Terminate() for all running processes and it works fine! 
Have no crash on close app right after opening.
So I revert logic back to immediately terminating from waiting for finish.

**Comment by engor** [comment]
H... Terminate raised a crash, so will waiting for finishing all.
(For testing, I opened all files from mojo module (to abuse parser at startup), then reopen IDE and close it quickly - got crash).

**Comment by blitz-research** [comment]
Good man!

Monkey2's GC memory management *should* be good enough to not have to deal
with recycling etc...that's the idea anyway.

Ted2go still going strong here 8 hours or so later...

**Comment by engor** [comment]
> Ted2go still going strong here 8 hours or so later...

Yeah!!
