### ISSUE TITLE
IntelliSense + Zoom out

### ISSUE THREAD

**Issue by Nju79** [engor/Ted2Go#53]
Hey,
there is a issue with IntelliSense in combination with zoom in. When I zoom in more than 2 times IntelliSense doesn't works correctly.
![issue](https://user-images.githubusercontent.com/32636068/31333652-30ec1e7a-aceb-11e7-916d-4f46ecb6e822.png)
 empty window.

**Comment by engor** [comment]
What's happen if you re-open autocompletion list?

**Comment by Nju79** [comment]
You mean when I stop writing (click another position), then continue writing at the original position? Same issue.

**Comment by Nju79** [comment]
Closed and reopened Ted didn't fix this issue.

System: Windows 8.1 (german), NVidia graphic with newest drivers.

**Comment by engor** [comment]
I just try to scale-up ide, then (re)open completion list and its size became bigger accordingly to scale factor.
![2017-10-09_17-35-21](https://user-images.githubusercontent.com/5233803/31334366-3ef2a570-ad18-11e7-838b-a031036a2896.png)

what version of ted2go do you use?

**Comment by Nju79** [comment]
Oh shit, my mistake! I mean "zoom out". The issue begins with the third letter. In your picture you typed 2 letters - that works one time. When I typing now the third letter, the issue begins (then for 2 letters too).

Next when  reset the zoom and type 2 letters, the issue remains. When I type the third letter IntelliSense working correctly then.

I use v2.7a (but the issue was in 2.7 too).

**Comment by engor** [comment]
Should be fixed now.

**Comment by Nju79** [comment]
yes, looks fine. Good work!
