### ISSUE TITLE
Broken capitalizing when press space

### ISSUE THREAD

**Issue by engor** [engor/Ted2Go#57]
If we have concatenated words and split them by space - have no capitalizing.

```
If a>b then|Print "a > b"
v v v
If a>b then Print "a > b"

```

**Comment by Nju79** [comment]
What's the use of this feature? :)

**Comment by engor** [comment]
It's a bug in latest release.

**Comment by Nju79** [comment]
Yeah, but for what I use capitalizing of concatenated words? :)

**Comment by engor** [comment]
For example, you have this line:
`view.Refresh()`
and then you decided to add IF-condition.
`If view Then view.Refresh()`
Type it in v2.7 and you will see that `if` didn't capitalized, because when you press space after if capitalizer see `if|view.Refresh()` - where | char is cursor position.
I think, write this comment is longer than fix bug. :) Will fix tomorrow.

**Comment by Nju79** [comment]
thx
