### ISSUE TITLE
IntelliSense + Zoom out #2

### ISSUE THREAD

**Issue by Nju79** [engor/Ted2Go#58]
Next bug with IntelliSense + Zoom out:

![bug2](https://user-images.githubusercontent.com/32636068/31583082-3c011e66-b194-11e7-9f17-61cc7429c0bc.png)

Best regards :)

**Comment by engor** [comment]
Did you use this zoom factor or set just for testing?

**Comment by Nju79** [comment]
I zoom the source 2-3 times out to code. When I use the standard zoom the font is to large for me. :)

**Comment by engor** [comment]
Should be fixed in dev branch.
