### ISSUE TITLE
IDE Can't handle german umlaute

### ISSUE THREAD

**Issue by Nju79** [engor/Ted2Go#59]
When I save a new file named with german umlaute, the IDE save this not named correctly.
e.g.:

![ide](https://user-images.githubusercontent.com/32636068/31632565-b544061a-b2bd-11e7-97e8-26ea91a1319d.png)

![filesystem](https://user-images.githubusercontent.com/32636068/31632574-bab8bf00-b2bd-11e7-9139-348d40c35c8d.png)

**Comment by engor** [comment]
I think it's monkey2 issue, there is `libc.fopen()` used to save data.
Interesting fact - it can save special chars (with incorrect name) but can't load it back.

Anyway, it's not good idea to use non-latin chars in filenames.

**Comment by engor** [comment]
@Nju79 I just tried to save file with name `Länge-mūsiz-ǣrende.monkey2` (don't know what is translation of this, sorry) - and it works fine.
Thanks to recent Mark's changes added utf8 for filesystem.
You can grab latest monkey2 dev branch to try it out.
