### ISSUE TITLE
[Feature request] Mouse cursor does not change when mousing over the text editor.

### ISSUE THREAD

**Issue by ImmutableOctet** [engor/Ted2Go#60]
As the title suggests, the mouse cursor does not change to the 'I' text select cursor when moving the mouse over the text area. Mojo2 and by extension, MojoX, use SDL2, so this is possible with a few SDL2 calls.

Something like this:
```

			#Import "<sdl2>"
			
			' Hold a pointer to the SDL mouse cursor:
			Field text_cursor:sdl2.SDL_Cursor Ptr
			
			' ...
			
			' On startup/construction, create the system cursor:
			text_cursor = sdl2.SDL_CreateSystemCursor(sdl2.SDL_SYSTEM_CURSOR_IBEAM)
			
			' Add an override for 'OnMouseEvent' to the text view:
			sdl2.SDL_SetCursor(text_cursor)
			
			' ...
			
			' When releasing resources:
			'sdl2.SDL_FreeCursor(text_cursor)
```

The only thing I'm not too sure about is how to check if the cursor has left the text-view, which would allow us to set the cursor back to normal for everything else.

From what I gather, MojoX manages 'View' bounds-checking, so detecting if the mouse cursor left the view might be something that's not implemented yet.

**Comment by engor** [comment]
Cursor changing to IBeam but for code files only.
