### ISSUE TITLE
Can't build latest

### ISSUE THREAD

**Issue by DoctorWhoof** [engor/Ted2Go#63]
Hi, some file names don't match the code in the latest dev branch?
```
Parsing...
/Applications/Blitz/Ted2Go/Ted2.monkey2 [38] : Error : File not found "/Applications/Blitz/Ted2Go/dialog/LiveTemplateDialog.monkey2"
/Applications/Blitz/Ted2Go/Ted2.monkey2 [119] : Error : File not found "/Applications/Blitz/Ted2Go/DraggableTabs.monkey2"
```

**Comment by engor** [comment]
Try to clean project

![2017-11-06_18-42-13](https://user-images.githubusercontent.com/5233803/32439706-70b8b534-c322-11e7-8b34-e3cc4e292458.png)

**Comment by DoctorWhoof** [comment]
Thanks, I'll try when I get home.

But I can actually see an issue in the code on Github, line 38 in Ted2.Monkey2 says "dialog/LiveTemplateDialog", while the actual file name is different, "dialog/LiveTemplatesDialog" (notice that is says "Templates", plural)

**Comment by engor** [comment]
Please, remove or comment this line. It's unused. Templates are in preferences dialog.

**Comment by engor** [comment]
Monkey2 checks for incorrect imports (fixed?), nice!

**Comment by blitz-research** [comment]
The latest monkey2 develop branch should have corrected Ted2.monkey2 in
ted2go dir - does it not?

I haven't made this change to 'real' ted2go repos yet though.

**Comment by engor** [comment]
I see commit "Finally added build errors for #import file not found."
I will check & clean ted2go according to that. My repo have some dead/forgotten imports.

**Comment by engor** [comment]
I pushed fix into dev-branch.
