### ISSUE TITLE
Many errors "File not found" from new mx2cc

### ISSUE THREAD

**Issue by engor** [engor/Ted2Go#64]
Issue with ted2go parse-on-the-fly and new mx2cc.
* ted2go create temporary files to parse them (in tmp/ folder)
* mx2cc produces "File not found" errors because relative imported paths became incorrect.

How to fix that? Maybe to deny such errors for `geninfo` stage. Or something better?
@blitz-research

**Comment by blitz-research** [comment]
I can add a quick hack to disable these errors when geninfo-ing if you want?

Longer term, I guess we're gonna have to pass 2 filenames to mx2cc
somehow...

**Comment by engor** [comment]
2 filenames sounds good. :)

**Comment by engor** [comment]
But quick hack for geninfo looks easy and enough.
I also fixed an 'issue' in parsing - now ted2go copying into tmp/ only dirty files, not them all.

**Comment by blitz-research** [comment]
Quick hack done!

**Comment by engor** [comment]
Fixed on mx2cc side.
