### ISSUE TITLE
Help issues?

### ISSUE THREAD

**Issue by blitz-research** [engor/Ted2Go#66]
Hi,

Just playing around with the help system a bit and have a few issues:

* F1 help doesn't seem to always work. If I hit F1 on 'Canvas', it shows me the file/line it is declared in in the status bar, but no actual help page. I can find the page in the help tree though. F1 on 'DrawImage' works OK, could it be an issue with classes only?

* Browsing the help tree isn't working. If I start ted2go and open the topmost help tree nodes: assimp->assimp->Structs->alColor4D->Fields and then click on 'a' it  actually shows the page for 'aiColor4D'. It also 'highlights' aiColor4D in the tree. Ditto as I click on 'b', 'g' and 'a', you can see the nodes being hjghlighted are  'out of sync' with the nodes actually being clicked. This may be something to do with newdocs though.

Thats it for now...

Bye!
Mark

**Comment by engor** [comment]
Hi, I've pushed fix into `dev`, please try it out.
