### ISSUE TITLE
Json hilighting

### ISSUE THREAD

**Issue by DoctorWhoof** [engor/Ted2Go#71]
Hi,

Would it be possible to allow .json files to be highlighted using the same rules as .monkey2 files, instead of being handled as a text file?

It seems to almost work already as it is (when I save a .json file as .monkey2, just to see how it would work), the only exception being the curly bracket causing an error:

![jsonhilighting](https://user-images.githubusercontent.com/6250116/33244322-f275cc2e-d2a9-11e7-9507-c5df36b3f326.gif)

I've been editing a lot of .glsl and .json files directly in Ted2Go recently, it's just much easier than switching editors all the time. Little things like this would be much appreciated. Thanks!

**Comment by engor** [comment]
Done in dev branch.
It would be nice to navigating json by clicking nodes in Source tree view, but it's not trivial thing to extract values positions from their text representation.

**Comment by engor** [comment]
Yeah! I got nodes jumping too!

**Comment by DoctorWhoof** [comment]
Yay! Trying it out now.

**Comment by DoctorWhoof** [comment]
Hilighting works, Thanks!
Node jumping (in "Source" tab, I assume?) almost works... failing in object arrays. Try it in the attached zip file if you need an example.

Thanks!!!

[pixelPerfect.json.zip](https://github.com/engor/Ted2Go/files/1504787/pixelPerfect.json.zip)

**Comment by engor** [comment]
I done one more attempt.
Now it tries to jump to arrays values, but there can be incorrect positions found when we have the same subnodes names...

**Comment by engor** [comment]
The easiest way to get correct jumping is to add text positions right inside of JsonValue.
Maybe... ever... :)

**Comment by DoctorWhoof** [comment]
Don't worry about it, this is already more than what I asked for.
Thanks!

**Comment by engor** [comment]
Have a good coding! ;)
