### ISSUE TITLE
Update/rebuild modules crashes after deleting a module.

### ISSUE THREAD

**Issue by blitz-research** [engor/Ted2Go#78]
Hi,

Update/rebuild modules crashes after deleting a module.

[edit]Actually, this looks like an mx2cc thing!

Bye,
Mark

**Comment by engor** [comment]
Why closed? I'm facing the bug.

**Comment by blitz-research** [comment]
Yes, just noticed that was fixed, thanks.

Love the draggable tabs too, that must have been some funky coding!

**Comment by engor** [comment]
Thanks. :)

> Love the draggable tabs too, that must have been some funky coding!

But now we have drag-n-drop code base for other stuff.
And did you try drag-n-drop in Project files tree? It also is here.

**Comment by blitz-research** [comment]
> Why closed? I'm facing the bug.

The crash happens when a module.json 'depends' array has a reference to a non-existant module.

**Comment by engor** [comment]
That's it.. And you'll fix that?

**Comment by blitz-research** [comment]
Just after this beer...

**Comment by blitz-research** [comment]
I bet it's related to operator[] returning Null for Maps too!

**Comment by engor** [comment]
`... Eachin deps[cur]`
