### ISSUE TITLE
The running application is not relaunched when pressing the build/run button while stopped.

### ISSUE THREAD

**Issue by ImmutableOctet** [engor/Ted2Go#8]
When debugging, I tend to modify various files as I read debug information. Normally this ends with me taking a while and not seeing that the program's still running, and I hit the build/run button to rebuild. Ted2Go currently does not care about executing builds and instead tries to rebuild... Which is fine, and in fact, what I'd expect it to do, but it doesn't seem to close the running process. This results in native build errors.

Since there's a "debug-kill" button, I assume there's a way to stop the running program before building again, right? Is it possible to essentially perform that function when the build/run button (Or F5) is pressed? This would help a lot when debugging.

**Comment by engor** [comment]
I think we can add Ctrl+F5 shurtcut to restart process.
Added to tasks.

**Comment by ImmutableOctet** [comment]
Restarting's not the issue, though. Rebuild is. In other words, hitting F5 again should close the running build and do what it currently does, which is restart the build process.

The problem right now is that hitting F5 won't first kill the debugged program, meaning I have to click the stop button, then hit the build button, which is counter intuitive.

I'm just asking for the stop function to be performed, that's all.

**Comment by engor** [comment]
Ok, I understand you.

**Comment by ImmutableOctet** [comment]
Actually, as a follow-up question, how do you feel about the run button itself (Not F5) just continuing execution like Ted 1 used to? That basically makes it function like a big continue button while debugging.

This whole thing started from me hitting F5 out of habit anyway, so if F5 could work as the stop and rebuild button, and the big green button would change its function into a continue button, then you'd get accurate behavior to Ted 1.

Just an idea. Either way, F5 should definitely kill the running build, though.

**Comment by engor** [comment]
Good idea, will try to implement.

**Comment by engor** [comment]
Added "Force stop" before build now. Debugger steps - later.
