### ISSUE TITLE
dev crashing a lot

### ISSUE THREAD

**Issue by blitz-research** [engor/Ted2Go#80]
Hi,

I am finding the latest dev branch crashes quite often  when hitting F5 to run. And always so far without saving the current file first, whcih is very annoying! Will keep experimenting...

Also, unrelated thing, but if you use 'save' to change filetype, the editor thinks it's still the old type.

For example, create a file, save it as blah.cpp, and ted2go still capitalizes keywords etc.

I remember this being actually quite tricky to do with Ted2, I think in the end I just effective reloaded the entire file with a kludge added to keep tab pos the same.

Bye,
Mark

**Comment by engor** [comment]
I got a crash by F5 in fullscreen editor mode, and you?

**Comment by engor** [comment]
I fixed that #81.
Hope you can find crashes reason. :)

**Comment by blitz-research** [comment]
Hasn't happened for ages...

**Comment by blitz-research** [comment]
Ok, happening again and I think I know the problem!

It happens if you hit 'Run' after the program stops in the debugger and you don't hit the little square 'Stop' button first.

I think this may actually be related to a 'fix' I proposed a while back, but can you take a look?

**Comment by engor** [comment]
Will take a look.
As I remember we added
if console.running then console.stop ()
Maybe we need to wait process to be fully stopped.. if it stops not immediately.

**Comment by blitz-research** [comment]
Ok, found it, Process.Terminate could sometimes crash when you tried to terminate an already finished process. Fixed in std.process native files.

Ted2go terminates console process just before debugging an app, but console process has always just have finished building, so it was kind of pointless but still should haven't killed everything!

**Comment by engor** [comment]
Very nice!
