### ISSUE TITLE
Strange bug in Rightclick Menu

### ISSUE THREAD

**Issue by DrCox85** [engor/Ted2Go#82]
Sometimes when I mark something and then right click, 
the mark disappears.
![rightclick issue](https://user-images.githubusercontent.com/10388962/33786309-ea433cee-dc68-11e7-801e-165e41400aee.gif)

**Comment by engor** [comment]
It happens when your click right position is greater than selection-end right position.
Even if ckicked inside of selection.
Will try to fix.
