### ISSUE TITLE
Errors open fake files (import name vs actual name)

### ISSUE THREAD

**Issue by forgotten-king** [engor/Ted2Go#84]
If there is an error in a file, Ted2Go will not open a duplicate, fake, file with the wrong name if the `#import filename` has a different capitalization.

# As shown in this image:
![image](https://user-images.githubusercontent.com/29788070/33863317-5f53971c-dea4-11e7-8a62-3013ebb4822a.png)

Steps to reproduce:
1. Create a main file
2. Create a dummy file with an error 
3. In the main file, `#Import ` the dummy file, but make sure it's capitalized differently.
4. Running the program will now open the correct file contents, but it's not pointing to the correct file name
5. If you have the (real) dummy file opened in Ted there will be two of the same file, both out of sync.

**Comment by engor** [comment]
Hm, Windows has case-insensitive file system, it produces many troubles..
I'm going to do a bit dirty hack - to check opened documents by lowercasing them.
Is good solution?
Maybe someone knows how to check filenames case-sensitive way?

**Comment by engor** [comment]
Invented!! :)
```
Function GetCaseSensitivePath:String( path:String )

#If __HOSTOS__="windows"
	Local dir:=ExtractDir( path )
	Local items:=LoadDir( dir )
	If items
		Local lower:=StripDir( path ).ToLower()
		For Local i:=Eachin items
			If i.ToLower()=lower Return dir+i
		Next
	Endif
	Return path
#Else
	Return path
#Endif
End
```
Will works correct now.
**But it's strongly recommended to use proper files casing** to be able to build for macos and linux.
