### ISSUE TITLE
Update modules

### ISSUE THREAD

**Issue by blitz-research** [engor/Ted2Go#86]
Hi,

Would it possible for the update modules dialog to remember what modules/targets/configs etc were selected? Doesn't even need to save state when IDE closes really, just as long as reopening dialog doesn't reset last choices.

This would greatly help with module development. I currently alt-tab to a dos shell and hit 'up arrow/return' to quickly build individual modules (mostly out of habit), but this is clumsy and means I have to manually find error lines too.

Bye!
Mark

**Comment by engor** [comment]
Hi, will do. :)

**Comment by blitz-research** [comment]
90% there - it's not remembering target.

**Comment by engor** [comment]
Fixed.

**Comment by blitz-research** [comment]
Thanks!

On Mon, Dec 18, 2017 at 8:12 PM, Evgeniy Goroshkin <notifications@github.com
