### ISSUE TITLE
Interesting crash!

### ISSUE THREAD

**Issue by DruggedBunny** [engor/Ted2Go#89]
While attempting to port some BlitzMax code, I ran into a crash when moving the cursor within a particular line -- Ted2Go just silently exits!

Note that this code is NOT all mx2, as I'm just going through fixing errors as I find them!

EDIT: This is enough to show the problem:

`  data[in$.length Shr 2] = data[in$.length Shr 2] | ($80 Shl ((in$.length & 3) Shl 3)) `

It crashes when I place the cursor near the third instance of `in$`, using either cursors or mouse.

Just paste this into a new tab and click within the last `in$.length`.

(I'm using the dev version from last week at the moment.)

**Comment by DruggedBunny** [comment]
Narrowed down a little more:

```
($80 Shl ((in$.length & 3) Shl 3))

$80 Shl ((in$.length & 3) Shl 3)

```
The first line crashes, while the second line (outer brackers removed) is fine...

**Comment by engor** [comment]
Do you use the latest v2.8 from itch.io?
I fixed that bug with brackets a few days ago.

**Comment by DruggedBunny** [comment]
OK, just updated to latest and it is indeed fixed -- thanks!
