### ISSUE TITLE
Green-highlighted lines for debugging cannot be removed without breaking the text-view

### ISSUE THREAD

**Issue by ImmutableOctet** [engor/Ted2Go#9]
Kind of a weird corner case, but if you're editing a file that's say, small enough for an example, you can't remove the green line that's currently being debugged. Doing so breaks all text rendering for some weird reason. Given, I found this out of laziness, but it's still a really weird bug.

Here's some example source:

```
Function Main:Void()
	F()
End

Function F:Void()
	DebugStop()
	
	Local x:= 10
	
	Print(x)
End
```

The definition for 'x' should be highlighted green. Now, simply delete the green line completely. This should move the line back to line 7, but instead, it stops displaying text completely.

Here's a gif of this happening:
![2016-12-02_08-57-39-hf](https://cloud.githubusercontent.com/assets/3187882/20840444/8415f92c-b86d-11e6-8d4b-ad97c3107622.gif)

**Comment by engor** [comment]
Fixed in 'dev'. Yep!
