### ISSUE TITLE
Long text is very bugged

### ISSUE THREAD

**Issue by forgotten-king** [engor/Ted2Go#91]
For some reason, the cursor is drawn a lot further away from where it actually is. It tends to be most noticeable with long non-space delimited text. Take, for example, this text:

111222333444555666777888999111222333444555666777888999111

Just mess around with this for a bit, don't put any spaces, and mostly pay attention to the end. It's all wrong. 

I noticed because:
```monkey
#Import "<pyro-scenegraph>"
```
Had a weird space between the `h` and the `>` which wasn't actually there. 
notice:
![image](https://user-images.githubusercontent.com/29788070/34318176-74fe461a-e77e-11e7-990c-6de9b0e09f98.png)
(there are no "textual" spaces in either of those examples)

- Windows 10
- v2.8

**Comment by blitz-research** [comment]
Not getting anything like that here - are you using a custom font or theme?

**Comment by forgotten-king** [comment]
Sorry forgot that I was using a custom font! 

It's `Menlo-Regular` normal font.

**Comment by engor** [comment]
What to do this that?
I suppose it's a **mojox** issue?

**Comment by forgotten-king** [comment]
This doesn't happen in the latest release! So I'll close this for now :)
