### ISSUE TITLE
Minor focus issue

### ISSUE THREAD

**Issue by blitz-research** [engor/Ted2Go#92]
Hi,

It's a minor thing, but when you double click a file on the project treeview to open it, it doesn't get key focus.

The cursor does actually appear to blink once in the newly opened file, but then it's gone...

Bye,
Mark

**Comment by engor** [comment]
Hi. 
Is there single click mode enabled for project tree? If files open by single click, then the second click moves focus to project view - and you can press delete key to delete file.

**Comment by blitz-research** [comment]
Nope, I have to double click to open a file.

And it does get the focus for about 1 'cursor blink' - then the cursor
disappears and no focus. Should be fairly easy to reproduce?

Could quite easily be a mojox thing  too....


On Tue, Dec 26, 2017 at 3:08 PM, Evgeniy Goroshkin <notifications@github.com

**Comment by engor** [comment]
And SiblyMode is off too?

**Comment by engor** [comment]
Should be fixed now in `dev`.
