### ISSUE TITLE
[Feature Request] Better Project Management 

### ISSUE THREAD

**Issue by abe-noll** [engor/Ted2Go#94]
Currently, projects are all clumped together in one long list and when you start working on various projects the container starts to become rather cluttered/noisy. I have some feature suggestions which can hopefully circumvent this problem.

<ol>
  <li>
    Create separate instances of Ted2 so that each opened project has its own window ...
    <ul>
      <li>
        This doesn't need to be a new window for *every* project, just whichever was opened in a new window
      </li>
      <li>
        Opening up ted2go should probably know how many project windows were last active
      </li>
    </ul>
  </li>
  <li>
    Create an archival system/focusing system
    <ul>
      <li>
        IE: Right click on an open project -> archive project
      </li>
      <li>
        If projects are archived, they're filtered out of the view
        <ol>
          <li>
            There could be a button in the view which allows you to toggle visibility of archived projects?
          </li>
        </ol>
      </li>
    </ul>
  </li>
  <li>
    A combination of both! This would allow switching between projects with different views of n-many projects
  </li>
</ol>

Thanks for your time and consideration, Abe

**Comment by engor** [comment]
I will see. Proj management is important thing.

**Comment by engor** [comment]
Recently I added project system - now we can use .mx2proj files along with folder-based projects.
You can switch active project by right-click on it in project view and choose "Set as main project".
Also you can set up main file of project once and forget about locking files everytime and keep them opened.

I dislike archiving stuff - you can just close project and reopen it later.

So close the issue. :)
