### ISSUE TITLE
Other way for ide

### ISSUE THREAD

**Issue by Alexey-T** [engor/Ted2Go#95]
Maybe consider to make ide for Monkey as addons for CudaText. Plugins written in python , and Monkey lexer. It’s hard?

**Comment by engor** [comment]
I don't know is it hard or not. 
You can try to add support of monkey2 yourself if you like that editor. :)
I like Ted2Go.

**Comment by Alexey-T** [comment]
i think it's easier to write IDE in this way based on CudaText.
