### ISSUE TITLE
Bug when using "Stop Process"

### ISSUE THREAD

**Issue by engor** [engor/Ted2Go#97]
Bug when using "Stop Process"
Ted2Go then takes you to some seemingly random place in some source file, even though there was no error, just me stopping the app

http://hezkore.com/captures/x_u1514862655.gif

**Comment by engor** [comment]
Are anyone facing it now?

**Comment by blitz-research** [comment]
Hasn't happened here for a while...

On Sun, Feb 25, 2018 at 2:50 AM, Evgeniy Goroshkin <notifications@github.com
